ots_billing_home:
    path:     /
    defaults: 
        _controller: OTSBillingBundle:Billing:index
    methods:  [GET, POST]

ots_billing_thanks:
    path:     /confirmation
    defaults: 
        _controller: OTSBillingBundle:Billing:confirmation
    methods:  [GET]
