services:
    ots_billing.form.flow.ticketOrder:
        class: OTS\BillingBundle\Form\TicketOrderFlow
        parent: craue.form.flow
        arguments:
            - "@translator"

    ots_billing.manager.stock_manager:
        class: OTS\BillingBundle\Manager\StockManager
        arguments:
            - "@doctrine.orm.entity_manager"

    ots_billing.manager.customer_manager:
        class: OTS\BillingBundle\Manager\CustomerManager

    ots_billing.manager.charge_manager:
        class: OTS\BillingBundle\Manager\ChargeManager

    ots_billing.manager.order_manager:
        class: OTS\BillingBundle\Manager\OrderManager
        arguments:
            - "@translator"
            - "@validator"
            - "@ots_billing.billing_form.error_return"

    ots_billing.manager.entity_manager:
        class: OTS\BillingBundle\Manager\EntityManager
        arguments:
            - "@ots_billing.manager.order_manager"

    ots_billing.stripe.stripe_service:
        class: OTS\BillingBundle\Service\Stripe\StripeService
        arguments:
            - "@translator"
            - "@ots_billing.billing_form.error_return"

    ots_billing.mailer.mailer_notificator:
        class: OTS\BillingBundle\Service\Mailer\MailerNotificator
        arguments:
            - "@mailer"
            - "@twig"
            - "@translator"

    ots_billing.billing_form.error_return:
        class: OTS\BillingBundle\Service\BillingForm\ErrorReturn
        arguments:
            - "@request_stack"
            - "@twig"

    ots_billing.listener.checkout_listener:
        class: OTS\BillingBundle\Listener\CheckoutListener
        arguments:
            - "@ots_billing.mailer.mailer_notificator"
            - "@ots_billing.manager.stock_manager"
        tags:
            - { name: kernel.event_listener, event: ots_billing.successful_checkout, method: processCheckoutSuccess }
    
    ots_billing.listener.submitted_order_listener:
        class: OTS\BillingBundle\Listener\SubmittedOrderListener
        arguments:
            - "@ots_billing.manager.stock_manager"
            - "@ots_billing.manager.order_manager"
            - "@ots_billing.manager.customer_manager"
            - "@ots_billing.manager.charge_manager"
            - "@ots_billing.manager.entity_manager"
            - "@ots_billing.stripe.stripe_service"
            - "@translator"
            - "@ots_billing.billing_form.error_return"
        tags:
            - { name: kernel.event_listener, event: ots_billing.submitted_order, method: processSubmittedOrder }
