services:
    ots_billing.form.flow.ticketOrder:
        class: OTS\BillingBundle\Form\TicketOrderFlow
        parent: craue.form.flow
        arguments:
            - "@service_container"

    ots_billing.stock.stock_manager:
        class: OTS\BillingBundle\Service\Stock\StockManager
        arguments:
            - "@doctrine.orm.entity_manager"

    ots_billing.billing.order_checker:
        class: OTS\BillingBundle\Service\Billing\OrderChecker

    ots_billing.charge.charge_manager:
        class: OTS\BillingBundle\Service\Charge\ChargeManager

    ots_billing.mailer.mailer_notificator:
        class: OTS\BillingBundle\Service\Mailer\MailerNotificator
        arguments:
            - "@mailer"
            - "@twig"
            - "@service_container"

    ots_billing.listener.checkout_listener:
        class: OTS\BillingBundle\Listener\CheckoutListener
        arguments:
            - "@ots_billing.mailer.mailer_notificator"
            - "@ots_billing.stock.stock_manager"
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: ots_billing.successful_checkout, method: processCheckoutSuccess }