services:
    ots_billing.form.flow.ticketOrder:
        class: OTS\BillingBundle\Form\TicketOrderFlow
        parent: craue.form.flow
        arguments:
            - "@service_container"

    ots_billing.mailer.checkout_notificator:
        class: OTS\BillingBundle\Mailer\CheckoutNotificator
        arguments:
            - "@mailer"
            - "@twig"
            - "@service_container"

    ots_billing.mailer.checkout_stock_manager:
        class: OTS\BillingBundle\Mailer\CheckoutStockManager
        arguments:
            - "@doctrine.orm.entity_manager"

    ots_billing.mailer.checkout_listener:
        class: OTS\BillingBundle\Mailer\CheckoutListener
        arguments:
            - "@ots_billing.mailer.checkout_notificator"
            - "@ots_billing.mailer.checkout_stock_manager"
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: ots_billing.successful_checkout, method: processCheckoutSuccess }