services:
    ots_billing.form.flow.ticketOrder:
        class: OTS\BillingBundle\Form\TicketOrderFlow
        parent: craue.form.flow
        arguments:
            - "@translator"

    ots_billing.entity.stock_manager:
        class: OTS\BillingBundle\Service\Entity\StockManager
        arguments:
            - "@doctrine.orm.entity_manager"

    ots_billing.entity.customer_manager:
        class: OTS\BillingBundle\Service\Entity\CustomerManager

    ots_billing.entity.charge_manager:
        class: OTS\BillingBundle\Service\Entity\ChargeManager

    ots_billing.entity.order_manager:
        class: OTS\BillingBundle\Service\Entity\OrderManager
        arguments:
            - "@translator"
            - "@request_stack"
            - "@validator"
            - "@twig"

    ots_billing.entity.entity_manager:
        class: OTS\BillingBundle\Service\Entity\EntityManager
        arguments:
            - "@ots_billing.entity.order_manager"

    ots_billing.stripe.stripe_manager:
        class: OTS\BillingBundle\Service\Stripe\StripeManager
        arguments:
            - "@translator"
            - "@request_stack"

    ots_billing.mailer.mailer_notificator:
        class: OTS\BillingBundle\Service\Mailer\MailerNotificator
        arguments:
            - "@mailer"
            - "@twig"
            - "@translator"

    ots_billing.listener.checkout_listener:
        class: OTS\BillingBundle\Listener\CheckoutListener
        arguments:
            - "@ots_billing.mailer.mailer_notificator"
            - "@ots_billing.entity.stock_manager"
        tags:
            - { name: kernel.event_listener, event: ots_billing.successful_checkout, method: processCheckoutSuccess }
    
    ots_billing.listener.submitted_order_listener:
        class: OTS\BillingBundle\Listener\SubmittedOrderListener
        arguments:
            - "@ots_billing.entity.stock_manager"
            - "@ots_billing.entity.order_manager"
            - "@ots_billing.entity.customer_manager"
            - "@ots_billing.entity.charge_manager"
            - "@ots_billing.entity.entity_manager"
            - "@ots_billing.stripe.stripe_manager"
            - "@translator"
            - "@twig"
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: ots_billing.submitted_order, method: processSubmittedOrder }
