services:
    ots_billing.form.flow.ticketOrder:
        class: OTS\BillingBundle\Form\TicketOrderFlow
        parent: craue.form.flow
        arguments:
            - "@service_container"

    ots_billing.stock.stock_manager:
        class: OTS\BillingBundle\Service\Stock\StockManager
        arguments:
            - "@doctrine.orm.entity_manager"

    ots_billing.order.order_manager:
        class: OTS\BillingBundle\Service\Billing\OrderManager
        arguments:
            - "@translator"
            - "@request_stack"

    ots_billing.stripe.stripe_manager:
        class: OTS\BillingBundle\Service\Stripe\StripeManager
        arguments:
            - "@translator"
            - "@request_stack"

    ots_billing.mailer.mailer_notificator:
        class: OTS\BillingBundle\Service\Mailer\MailerNotificator
        arguments:
            - "@mailer"
            - "@twig"
            - "@translator"

    ots_billing.listener.checkout_listener:
        class: OTS\BillingBundle\Listener\CheckoutListener
        arguments:
            - "@ots_billing.mailer.mailer_notificator"
            - "@ots_billing.stock.stock_manager"
        tags:
            - { name: kernel.event_listener, event: ots_billing.successful_checkout, method: processCheckoutSuccess }