ots_core:
    resource: "@OTSCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr

ots_billing:
    resource: "@OTSBillingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/booking
    requirements:
        _locale: en|fr

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
