ots_core:
    resource: "@OTSCoreBundle/Controller/"
    type:     annotation

ots_billing:
    resource: "@OTSBillingBundle/Controller/"
    type:     annotation

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
