<?php

namespace OTS\BillingBundle\Repository;

/**
 * TicketOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
