ots_core_home:
    path:     /
    defaults: 
        _controller: OTSCoreBundle:Core:index
    methods:  [GET]

ots_core_legal:
    path:     /legal
    defaults:
        _controller: OTSCoreBundle:Core:legal
    methods:  [GET]

ots_core_terms:
    path:     /terms
    defaults:
        _controller: OTSCoreBundle:Core:terms
    methods:  [GET]
